# Generated by Django 5.0.6 on 2024-05-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
