# Generated by Django 5.0.6 on 2024-05-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload_date',
        ),
    ]
